### ISSUE TITLE
V3.1.7 is my best

### ISSUE THREAD

**Issue by HOPS0914** [shyrodgau/imbraw2dng#2]
The imbraw2dng you released is a great tool and I use it regularly !!
When developing a photo, we understand that if the original image is degraded, it will be less effective, so raw images are very effective. Even 8-bit images are better than the unexpected degradation caused by jpeg compression.

However, the best imbraw2dng version in my environment is V3.1.7. :-)
I have attached my report for a later version, so I hope it will be helpful to you.

Thank you again.

[imbraw2dng_report_20240411.pdf](https://github.com/shyrodgau/imbraw2dng/files/14940562/imbraw2dng_report_20240411.pdf)

**Comment by shyrodgau** [comment]
Hm interesting, I had found a preview line misalignment for one of the MF formats, should be fixed in the latest version. Anyway now there should be a checkbox where you can de-select the preview. On my linux box, there is not even any way to benefit from the preview image (file explorer will not use it). But in order to check it, I had to build it first...

**Comment by HOPS0914** [comment]
V3.5.9 is my best (but without thumbnail :-) ...)

When I run it with a thumbnail, it is not recognized as an image.
It seems that the tag information is corrupted.

[imbraw2dng_report_20240415.pdf](https://github.com/shyrodgau/imbraw2dng/files/14973658/imbraw2dng_report_20240415.pdf)

I would appreciate it if you could refer to the attached pdf.
thank you.

**Comment by shyrodgau** [comment]
okay, there was a big bug in the case that the preview had a special size... maybe this even could fix the problem with the software that was not using the raw at all when a preview was embedded?

**Comment by HOPS0914** [comment]
Thank you for your early response.
V3.6.2_dev successfully converted RAW images to DNG with thumbnails! ! DNG without thumbnails can be converted successfully as well. 
your work is great. Thank you again.
--
TIFF/RAW Information Filename = 2024_0202_061913_003 (6).dng Filesize = 11,654,106 bytes
00000000 TIFF header 49492A0068860000 little endian (Intel)

00008668-000087ED 0th IFD Tag-32 Next IFD 00000000 (Value-00000000)
0000866A 00FE New subfile type reduction
00008676 0100 Image width 126
00008682 0101 Image height 91
0000868E 0102 Image bit depth 8 8 8 (bit)
0000869A 0103 Compression type Uncompressed
000086A6 0106 Pixel configuration RGB
000086B2 010F Manufacturer ImBack
000086BE 0110 Model name ImB35mm
000086CA 0111 Pointer to image data 00000008 (Value-00000008)
000086D6 0112 Image orientation First row is top, column is left (no rotation)
000086E2 0115 Number of components 3
000086EE 0116 Number of lines in strip 91
000086FA 0117 Strip data amount 34,398 bytes
00008706 011A Image width resolution 30
00008712 011B Image height resolution 30
0000871E 011C Image data arrangement Dot sequential Chunky format
0000872A 0131 Software name imbraw2dng V3.6.2_dev
00008736 0132 File modification date and time 2024:02:02 06:19:13
00008742 014A Pointer to Sub IFD 00B1D338
0000874E 9003 Generation date and time of current image data 2024:02:02 06:19:13
0000875A C612 DNG Version 1.2.0.0
00008766 C613 DNG Backward Version 1.2
00008772 C614 Unique Camera Model ImBack ImB35mm
0000877E C61D White Level 255
0000878A C621 Color Matrix 1 00008862-000088A9 9 entries
00008796 C628 As Shot Neutral 0.6 1 0.6
000087A2 C65A Calibration Illuminant 1 23
000087AE C68B Original Raw FileName 2024_0202_061913_003.raw
000087BA C6F3 (ASCII) Generic ImB conv profile Sig
000087C6 C6F4 (ASCII) Generic ImB conv profile Sig
000087D2 C714 (SRATIONAL) 000088AA-000088F1 9 entries
000087DE C71B (ASCII) 2024-04-15T22:48:21.848Z

00B1D338-00B1D3D9 Sub-0 IFD Tag-13
00B1D33A 00FE New subfile type standard
00B1D346 0100 Image width 4012
00B1D352 0101 Image height 2896
00B1D35E 0102 Image bit depth 8 (bit)
00B1D36A 0103 Compression type Uncompressed
00B1D376 0106 Pixel configuration CFA
00B1D382 0111 Pointer to image data 00008978 (Value-00008978)
00B1D38E 0115 Number of components 1
00B1D39A 0116 Number of lines in strip 2,896
00B1D3A6 0117 Strip data amount 11,618,752 bytes
00B1D3B2 011C Image data arrangement Dot sequential Chunky format
00B1D3BE 828D CFA Repeat Pattern Dim 2 2
00B1D3CA 828E CFA Pattern G R B G

TIFF/RAW Information end.

**Comment by HOPS0914** [comment]
35mm has been completely converted. I plan to use MF in earnest when the firmware is updated to support jpeg+raw. thanks so much!
