### ISSUE TITLE
imbapp.apk MF raw cannot be converted correctly

### ISSUE THREAD

**Issue by HOPS0914** [shyrodgau/imbraw2dng#3]
Hello,
imbapp.apk converts RAW images taken with MF correctly so that they are recognized as images, but images taken with 35 are not recognized.

I tried several versions but the results were the same.
V5.3.8_7630603
V5.3.5_6c9d367
V5.1.1_0d68032

The html version of imbraw2dng.html (local file),
https://shyrodgau.github.io/imbraw2dng/imbapp.htm
has been confirmed to work correctly.
I am using an Android 14 Pixel 7 Pro.

I have attached the file for reference.
2024_1105_070716_033.RAW (image taken with 35 as original)
2024_1105_070716_033.dng (dng converted with apk)
2024_1105_070716_033_html.dng (dng converted with html)

If you have any questions, please feel free to ask.
(Please forgive me for the delay in replying when I am busy)

This imbapp.apk is the most useful tool for me.
I would be happy if it can be used with 35 as well as MF.

Thank you.
[2024_1105_070716_033.zip](https://github.com/user-attachments/files/17626096/2024_1105_070716_033.zip)
[2024_1105_070716_033_html.zip](https://github.com/user-attachments/files/17626099/2024_1105_070716_033_html.zip)

**Comment by shyrodgau** [comment]
Thank you, interesting! While I am investigating, I think that I have a workaround for you: convert RAW and JPEG in separate steps, RAW first. I can open both files without issues, but the file from the apk contains the exif data from the JPEG, and that seems to be buggy. When only RAW is converted without the JPEG, then that buggy exif data can not make it into the DNG and it should be better.

**Comment by shyrodgau** [comment]
The problem is found, it may take some time until I release it, need some regression tests

**Comment by shyrodgau** [comment]
Analysis: when copying the EXIF IFD from the JPEG into the DNG, there were a) some things cut off b) the fact that the interop tag references a separate IFD data block was not considered. Both issues were fixed.

**Comment by HOPS0914** [comment]
Thank you for your early response. 
I confirmed that RAW is successfully converted to DNG with the latest V5.3.9_e04e4fb. 
We will continue to use this useful tool. 
Thank you again.

**Comment by shyrodgau** [comment]
Unfortunately, the fix broke the JPEG download. Now also fixed.
